#!/bin/bash
#first prompt to enter the name of the folder to create
read -p 'Enter folder name : ' folder

#test if there is a folder with the same name and if a name has been writing (loop)
while [ -z $folder ] || [ -e $folder ]
do
        read -p 'choose another folder name, this one exists already :' folder
done

if [ ! -z $folder ] && [ ! -e $folder ]
then
        mkdir -p $folder
        echo "the file $folder  has been successfully created :) "
fi

cd $folder

#set the number of subfolder  you want to create 
read -p 'Enter the number of sub-folder you want to create : ' number

for n in `seq 1 $number`
do
        mkdir cours_$n
"test_01.sh" 28L, 695C                                                                                                       1,1           Top
